JUMP_THRESHOLD        = 0.10
SLIDE_ANGLE           = 130

SINGLE_HAND_UP        = 0.06
OPPOSITE_HAND_DOWN    = 0.05

SHIELD_CROSS          = 0.06

GESTURE_BUFFER_SIZE   = 5
GESTURE_CONFIRM_COUNT = 4

COOLDOWN_SECONDS      = 0.4

WEBCAM_WIDTH          = 640
WEBCAM_HEIGHT         = 480
TARGET_FPS            = 30
